version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geojson_platform_postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: geojson_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geojson_platform_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: geojson_platform_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
